#!/bin/sh

case "$1" in
    start)
        scull_load.sh
        module_load.sh faulty
        modprobe hello
        ;;
    stop)
        scull_unload.sh
        module_unload.sh faulty
        rmmod hello
        ;;
    *)
        echo "usage: $0 {start|stop}"
        exit 1
esac
